### ISSUE TITLE
'itunes' has no attribute 'search'

### ISSUE THREAD

**Issue by datamaskinen** [rickykresslein/kodkast#1]
Kubuntu 21.04
librarys installed:
  sudo pip install python-vlc
  sudo pip install peewee
  sudo pip install lxml
  sudo pip install iTunes
  sudo pip install validators
  sudo pip install BeautifulSoup4

terminal gives this:::

Traceback (most recent call last):
  File "/home/xxx/opt/kodkast/kodkast/kodkast.py", line 318, in <lambda>
    search_button = qtw.QPushButton('Search', clicked=lambda: self.search_itunes(search_box.text()))
  File "/home/xxx/opt/kodkast/kodkast/kodkast.py", line 375, in search_itunes
    results = itunes.search(query=search_query, media='podcast')
AttributeError: module 'itunes' has no attribute 'search'

**Comment by datamaskinen** [comment]
in appimage it works ... but the clone of repo it does not ... am i using wrong itunes library?

**Comment by rickykresslein** [comment]
Yeah, please try it with **sudo pip install pitunes**. That should fix the issue. Please let me know. And thanks for using Kodkast!

**Comment by datamaskinen** [comment]
Yupp now it's working..

it exaktly what i was looking for this ... clean and does it's thing ....
